label: 'BTEC baseline'
description: "multi-speaker baseline on BTEC, same configuration as Berard et al. 2016"

data_dir: data/BTEC_speech
model_dir: models/BTEC_speech/baseline
train_prefix: train.concat.shuf  # Michel, Philippe, Loic, Marion, Helene, Fabienne
max_train_size: 20000

optimizer: adam
learning_rate: 0.001
batch_size: 64
batch_mode: standard
read_ahead: 10
max_gradient_norm: 1.0
weight_scale: 0.1

steps_per_checkpoint: 1000
steps_per_eval: 1000
max_steps: 30000

cell_size: 256
attn_size: 256
cell_type: DropoutGRU

encoders:
  - name: feats41
    embedding_size: 41
    layers: 3
    time_pooling: [2, 2]
    pooling_avg: True
    binary: True
    attn_filters: 4
    attn_filter_length: 25
    max_len: 600
    input_layers: [256, 256]
    final_state: average
    train_initial_states: True
    bidir: True

decoders:
  - name: en
    layers: 2
    embedding_size: 256
    max_len: 25
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
rnn_output_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
use_lstm_full_state: False
