dropout_rate: 0.5
cell_size: 256
attn_size: 256
embedding_size: 128

layers: 1
bidir: True
use_lstm: False
max_output_len: 25
max_input_len: 25
weight_scale: 0.1

data_dir: data/btec
model_dir: models/btec_xent
batch_size: 32
dev_prefix: dev

optimizer: 'adam'

sgd_after_n_epoch: 20
learning_rate: 0.2
learning_rate_decay_factor: 0.9
decay_every_n_epoch: 1
decay_after_n_epoch: 21

steps_per_checkpoint: 1000
steps_per_eval: 1000

max_gradient_norm: 1.0
max_epochs: 0
batch_mode: 'standard'
read_ahead: 10

encoders:
  - name: fr

decoder:
    name: en
