label: 'BTEC debug'
description: "Debugging model"

cell_size: 128
attn_size: 128
embedding_size: 64

bidir: True
cell_type: GRU
weight_scale: 0.1

data_dir: data/BTEC
model_dir: models/debug
batch_size: 32

vocab_size: 2000

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 500
steps_per_eval: 500

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 10
max_len: 25
max_steps: 30000

encoders:
  - name: fr
    final_state: average

decoders:
  - name: en
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
rnn_output_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
