label: 'debug'
description: ''

data_dir: data/BTEC
model_dir: models/BTEC/debug


optimizer: adam
learning_rate: 0.001
batch_size: 64
batch_mode: standard
read_ahead: 10
max_gradient_norm: 5.0

steps_per_checkpoint: 1000
steps_per_eval: 1000
max_steps: 30000

cell_size: 256
attn_size: 256
embedding_size: 128
cell_type: LSTM

encoders:
  - name: fr
    bidir: True
    final_state: average
    max_len: 25

decoders:
  - name: en
    layers: 2
    max_len: 25

use_dropout: True
rnn_input_dropout: 0.5
initial_state_dropout: 0.5
input_layer_dropout: 0.5
reverse_input: True
