label: 'BTEC baseline'

cell_size: 256
attn_size: 256
embedding_size: 128

bidir: True
cell_type: GRU
embedding_weight_scale: 0.1
orthogonal_init: True

data_dir: data/BTEC
model_dir: models/debug
batch_size: 32

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000

batch_mode: standard
read_ahead: 10
max_len: 25
max_steps: 30000

encoders:
  - name: fr
    attn_heads: 4
    attn_size: 256
    cell_size: 1
    attn_mapping: 512
    attend_inputs: True
    average_inputs: True
    pos_embedding_size: 32
    max_len: 25

decoders:
  - name: en
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
attention_dropout: 0.2
word_dropout: 0.2
