label: 'debug'
description: "small BTEC config"

cell_size: 128
attn_size: 128
embedding_size: 64

layers: 1
bidir: True
use_lstm: True
weight_scale: 0.1

data_dir: data/BTEC
model_dir: models/debug
batch_size: 16
dev_prefix: dev

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 200
steps_per_eval: 200
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 10
max_len: 25

encoders:
  - name: fr

decoders:
  - name: en
