label: 'debug'
description: "small BTEC config"

dropout_rate: 0.0
cell_size: 128
attn_size: 128
embedding_size: 64

layers: 2
bidir: True
use_lstm: True
max_output_len: 25
max_input_len: 25
weight_scale: 0.1

data_dir: data/btec
model_dir: models/debug
batch_size: 32
dev_prefix: dev

optimizer: 'adam'
learning_rate: 0.001
#sgd_learning_rate: 0.2
#sgd_after_n_epoch: 4
#ecay_after_n_epoch: 2
#decay_every_n_epoch: 1
#learning_rate_decay_factor: 0.5

steps_per_checkpoint: 500
steps_per_eval: 500
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: 'standard'
read_ahead: 10

tasks:
  - encoders:
     - name: fr
    decoder:
       name: en

  - encoder:
     - name: en
    decoder:
       name: en
