label: 'Books baseline with joint subwords'

cell_size: 512
attn_size: 512
embedding_size: 256

bidir: True
cell_type: LSTM
weight_scale: 0.1

data_dir: data/books
model_dir: models/books/baseline
batch_size: 32

train_prefix: train
dev_prefix: [dev]
vocab_prefix: vocab

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 10
max_steps: 100000

encoders:
  - name: jsub.en
    final_state: average
    max_len: 62

decoders:
  - name: jsub.fr
    conditional_rnn: True
    pred_deep_layer: True
    deep_layer_size: 512
    max_len: 62

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
rnn_output_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
