label: 'ASR character-based baseline'

cell_size: 512
attn_size: 512
embedding_size: 256

bidir: True
cell_type: LSTM
weight_scale: 0.1

data_dir: data/audiobooks
model_dir: models/audiobooks/ASR/baseline_char
batch_size: 64

train_prefix: train
dev_prefix: [dev]
vocab_prefix: vocab

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 10
max_steps: 100000

encoders:
  - name: feats41
    final_state: concat_last
    bidir_projection: True
    train_initial_states: False
    max_len: 1000  # FIXME
    binary: True
    input_layers: [512, 256]
    input_layer_activation: tanh

decoders:
  - name: char.en
    conditional_rnn: True
    pred_deep_layer: True
    character_level: True
    use_previous_word: True
    deep_layer_size: 512
    embedding_size: 128
    max_len: 400

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
rnn_output_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
