label: 'ASR character-level baseline'

data_dir: data/audiobooks
model_dir: models/audiobooks/ASR/baseline_char
train_prefix: train.shuf
max_train_size: 20000
vocab_prefix: vocab

optimizer: adam
learning_rate: 0.001
batch_size: 32
batch_mode: standard
read_ahead: 10
max_gradient_norm: 5.0

steps_per_checkpoint: 2000
steps_per_eval: 2000
max_steps: 100000
score_function: corpus_scores_wer

cell_size: 256
attn_size: 256
cell_type: LSTM

encoders:
  - name: feats41
    embedding_size: 41
    layers: 3
    conv_filters: [16, 16]
    conv_size: [3, 3]
    conv_strides: [2, 2]
    conv_activation: relu
    binary: True
    max_len: 1500  # 90% coverage
    input_layers: [256, 128]
    input_layer_activation: tanh
    bidir_projection: True
    final_state: concat_last
    train_initial_states: False

decoders:
  - name: char.en
    layers: 2
    embedding_size: 64
    character_level: True
    max_len: 350  # 98% coverage
    pred_maxout_layer: False
    use_previous_word: False
    pred_embed_proj: False
    rnn_feed_attn: True

use_dropout: True
pervasive_dropout: True
attn_dropout: 0.4
rnn_input_dropout: 0.4
initial_state_dropout: 0.4
input_layer_dropout: 0.4
