label: 'IWSLT14 Baseline'
description: "IWSLT14 Baseline, similar dataset and model size as Ranzato et al. 2015 (MIXER)"
# scores   greedy    beam-size=8    Ranzato    Bahdanau
# dev      27.27     28.88
# test     24.78     26.22          20.73      22.34

cell_size: 256
attn_size: 256
embedding_size: 128

bidir: True
cell_type: LSTM
weight_scale: 0.1

data_dir: data/IWSLT14
model_dir: models/IWSLT14/baseline
batch_size: 32

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 20
max_len: 40
max_steps: 50000

encoders:
  - name: de
    final_state: average

decoders:
  - name: en
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: True
pervasive_dropout: False
rnn_input_dropout: 0.2
rnn_state_dropout: 0.0
attn_dropout: 0.2
word_dropout: 0.2
layer_norm: False
use_lstm_full_state: True