label: 'IWSLT14 Baseline'
description: "IWSLT14 Baseline, similar dataset and model size as Ranzato et al. 2015 (MIXER)"

cell_size: 256
attn_size: 256
embedding_size: 128

bidir: True
use_lstm: True
weight_scale: 0.1

data_dir: data/IWSLT14
model_dir: models/IWSLT14/baseline
batch_size: 32

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 20
max_len: 50
max_steps: 50000

encoders:
  - name: en
    final_state: average

decoders:
  - name: de
    conditional_rnn: True
    pred_deep_layer: True

use_dropout: False
pervasive_dropout: False
rnn_input_dropout: 0.2
rnn_state_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
layer_norm: False
