label: 'Books baseline from subwords to characters'
description: 'smaller model'

cell_size: 256
attn_size: 256
embedding_size: 128

bidir: True
cell_type: LSTM
weight_scale: 0.1

data_dir: data/audiobooks
model_dir: models/audiobooks/MT/sub2char.1
batch_size: 64

train_prefix: train
dev_prefix: [dev]
vocab_prefix: vocab

optimizer: adam
learning_rate: 0.001

steps_per_checkpoint: 1000
steps_per_eval: 1000
score_function: corpus_scores

max_gradient_norm: 1.0
batch_mode: standard
read_ahead: 10
max_steps: 100000

encoders:
  - name: sub.en
    final_state: average
    bidir_projection: False
    train_initial_states: True
    max_len: 60

decoders:
  - name: char.fr
    conditional_rnn: True
    pred_deep_layer: True
    character_level: True
    use_previous_word: True
    deep_layer_size: 256
    embedding_size: 128
    max_len: 400

use_dropout: True
pervasive_dropout: True
rnn_input_dropout: 0.2
rnn_output_dropout: 0.2
attn_dropout: 0.2
word_dropout: 0.2
initial_state_dropout: 0.2
